### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Unknown named parameter $name in /app/code/core/Mage/Core/Model/Layout.php:321

### ISSUE THREAD

**Issue by tim-breitenstein-it** [netresearch/dhl-module-versenden-m1#8]
### Requirements
- OpenMage v19.5.0
- PHP v8.1.x

Stack:
```
PHP Fatal error:  Uncaught Error: Unknown named parameter $name in /var/www/html/magento-dev/app/code/core/Mage/Core/Model/Layout.php:321
Stack trace:
#0 /var/www/html/magento-dev/app/code/core/Mage/Core/Model/Layout.php(210): Mage_Core_Model_Layout->_generateAction()
#1 /var/www/html/magento-dev/app/code/core/Mage/Core/Model/Layout.php(202): Mage_Core_Model_Layout->generateBlocks()
#2 /var/www/html/magento-dev/app/code/core/Mage/Core/Model/Layout.php(206): Mage_Core_Model_Layout->generateBlocks()
#3 /var/www/html/magento-dev/app/code/core/Mage/Core/Controller/Varien/Action.php(346): Mage_Core_Model_Layout->generateBlocks()
#4 /var/www/html/magento-dev/app/code/core/Mage/Core/Controller/Varien/Action.php(257): Mage_Core_Controller_Varien_Action->generateLayoutBlocks()
#5 /var/www/html/magento-dev/app/code/core/Mage/Adminhtml/Controller/Action.php(294): Mage_Core_Controller_Varien_Action->loadLayout()
#6 /var/www/html/magento-dev/app/code/core/Mage/Adminhtml/controllers/Sales/Order/ShipmentController.php(125): Mage_Adminhtml_Controller_Action->loadLayout()
#7 /var/www/html/magento-dev/app/code/core/Mage/Core/Controller/Varien/Action.php(422): Mage_Adminhtml_Sales_Order_ShipmentController->viewAction()
#8 /var/www/html/magento-dev/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(256): Mage_Core_Controller_Varien_Action->dispatch()
#9 /var/www/html/magento-dev/app/code/core/Mage/Core/Controller/Varien/Front.php(182): Mage_Core_Controller_Varien_Router_Standard->match()
#10 /var/www/html/magento-dev/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#11 /var/www/html/magento-dev/app/Mage.php(742): Mage_Core_Model_App->run()
#12 /var/www/html/magento-dev/index.php(55): Mage::run()
#13 {main}
thrown in /var/www/html/magento-dev/app/code/core/Mage/Core/Model/Layout.php on line 321,
referer: http://magento-dev.test/index.php/admin/admin/sales_order/view/order_id/123/active_tab/order_shipments/key/***************************/
```

Problem:
`/app/design/adminhtml/default/default/layout/dhl_versenden.xml`

```
                <action method="setTemplate">
                    <template helper="dhl_versenden/data/getPackagingPopupTemplate">
                        <name>dhl_versenden/sales/packaging_popup.phtml</name>
                        <block>shipment_packaging</block>
                    </template>
                </action>
...
                <action method="setTemplate">
                    <template helper="dhl_versenden/data/getPackagingPackedTemplate">
                        <name>dhl_versenden/sales/packaging_packed.phtml</name>
                        <block>shipment_packed</block>
                    </template>
                </action>
```

The helper function properties in the XML definition doesn´t match the helper class function arguments!

Solved by:
`/app/code/community/Dhl/Versenden/Helper/Data.php`

```
     /**
      * Get template name for packaging popup.
      *
-     * @param string $template dhl template
+     * @param string $name dhl template
      * @param string $block block name
      * @return string
      */
-    public function getPackagingPopupTemplate($template, $block)
+    public function getPackagingPopupTemplate($name, $block)
     {
         /** @var Mage_Adminhtml_Block_Sales_Order_Shipment_Packaging $blockObject */
         $blockObject = Mage::getSingleton('core/layout')->getBlock($block);
         $shippingMethod = $blockObject->getShipment()->getOrder()->getShippingMethod(true);

        if ($shippingMethod->getData('carrier_code') !== Dhl_Versenden_Model_Shipping_Carrier_Versenden::CODE) {
             // different carrier, return standard template
             return $blockObject->getTemplate();
         }

-        return $template;
+        return $name;
    }

     /**
      * Get template name for packaging packed info.
      *
-     * @param string $template dhl template
+     * @param string $name dhl template
      * @param string $block block name
      * @return string
      */
-    public function getPackagingPackedTemplate($template, $block)
+    public function getPackagingPackedTemplate($name, $block)
     {
         /** @var Mage_Adminhtml_Block_Sales_Order_Shipment_Packaging $blockObject */
         $blockObject = Mage::getSingleton('core/layout')->getBlock($block);
         $shippingMethod = $blockObject->getShipment()->getOrder()->getShippingMethod(true);

         if ($shippingMethod->getData('carrier_code') !== Dhl_Versenden_Model_Shipping_Carrier_Versenden::CODE) {
             // different carrier, return standard template
             return $blockObject->getTemplate();
         }

-        return $template;
+        return $name;
    }

```

**Comment by mam08ixo** [comment]
Confirmed, the extension is not compatible with PHP 8.
We will fix this and watch out for other compatibility issues.

**Comment by mam08ixo** [comment]
Version [1.12.0](https://github.com/netresearch/dhl-module-versenden-m1/releases/tag/1.12.0) fixes the issue.
